"use client"

import { useState } from 'react';
import { PDFDownloadLink } from '@react-pdf/renderer';

import { Button } from '@/components/ui/button';
import { fetchObbSheetDetails } from '@/actions/from-eliot/fetch-obb-sheet-details';
import { fetchGarmentDefectsWithOperations } from '@/actions/qc/gmt/fetch-garment-defects-with-operations';
import { fetchProductDefectsWithOperations } from '@/actions/qc/product/fetch-product-defects-with-operations';
import { calculateDhuAndAnalyzeDefects as gmtCalculationFunction } from '@/actions/qc/gmt/calculate-dhu-and-analyze-defects';
import { calculateDhuAndAnalyzeDefects as productCalculationFunction } from '@/actions/qc/product/calculate-dhu-and-analyze-defects';
import DayEndLineQcReportTemplate from '@/components/templates/report/day-end-line-allqc-report-template';
import DayEndLineQcReportViewer from '@/components/templates/report/viewer/day-end-line-allqc-report-viewer';
import SelectQcPointObbDateOptional from './common/select-qcpoint-obb-date-optional';

interface DayEndLineNonQcReportProps {
    scanningPoints: {
        id: string;
        name: string;
        pointNo: number;
    }[] | null;
    userName: string;
}

type ReportDetailsType = {
    label: string;
    value: string;
};

const DayEndLineNonQcReport = ({
    scanningPoints,
    userName
}: DayEndLineNonQcReportProps) => {
    const [pdfLink, setPdfLink] = useState<JSX.Element | null>(null);
    const [reportData, setReportData] = useState<{ label: string; data: HourlyQuantityFunctionReturnTypes }[]>([]);
    const [reportDetails, setReportDetails] = useState<ReportDetailsType[]>([]);


    const handleGenerateReport = async (data: { obbSheetId?: string; scanningPointId: string; pointNo: number; date: Date }) => {
        data.date.setDate(data.date.getDate() + 1);
        const formattedDate = data.date.toISOString().split('T')[0];

        const obbSheet = await fetchObbSheetDetails(data.obbSheetId ?? "");

        const garmentFrontDefects = await fetchGarmentDefectsWithOperations({ part: "front", date: formattedDate });
        const frontResults = gmtCalculationFunction(garmentFrontDefects);

        const garmentBackDefects = await fetchGarmentDefectsWithOperations({ part: "back", date: formattedDate });
        const backResults = gmtCalculationFunction(garmentBackDefects);
        
        const productAssemblyDefects = await fetchProductDefectsWithOperations({ part: "assembly", date: formattedDate });
        const assemblyResults = productCalculationFunction(productAssemblyDefects);

        const productLineEndDefects = await fetchProductDefectsWithOperations({ part: "line-end", date: formattedDate });
        const lineEndResults = productCalculationFunction(productLineEndDefects);
        
        const formattedData: { label: string; data: HourlyQuantityFunctionReturnTypes }[] = [
            { label: "Front QC", data: frontResults },
            { label: "Back QC", data: backResults },
            { label: "Assembly QC", data: assemblyResults },
            { label: "End QC", data: lineEndResults },
        ];

        const reportDetails = [
            { label: "Date", value: formattedDate },
            { label: "Generated By", value: userName },
            { label: "Style", value: obbSheet?.style ?? "-" },
            { label: "Buyer", value: obbSheet?.buyer ?? "-" },
            { label: "Color", value: obbSheet?.color ?? "-" },
            { label: "Unit", value: obbSheet?.unitName ?? "-" },
            { label: "Line", value: obbSheet?.lineName ?? "-" },
            { label: "Total DHU", value: formattedData.map(value => value.data.totalDHU).reduce((accumulator, currentValue) => accumulator + currentValue, 0).toFixed(2).toString() },
        ];

        setReportData(formattedData);
        setReportDetails(reportDetails);
        // console.log("AVG", reportDetails);

        const pdfElement = generatePdfReport(formattedData, reportDetails);
        setPdfLink(pdfElement);
    };

    const generatePdfReport = (reportData: any[], reportDetails: ReportDetailsType[]) => {
        return (
            <PDFDownloadLink
                document={
                    <DayEndLineQcReportTemplate
                        details={reportDetails}
                        data={reportData}
                    />
                }
                fileName="day-end-line-qc-report.pdf"
            >
                {/* {({ loading }) => (loading ? "Generating PDF..." : "Download PDF Report")} */}
                Download PDF Report
            </PDFDownloadLink>
        );
    };

    return (
        <div className="mt-8 mx-auto max-w-7xl">
            <SelectQcPointObbDateOptional
                scanningPoints={scanningPoints}
                handleSubmit={handleGenerateReport}
            />
            {(reportData.length > 0 && reportDetails.length > 0) &&
                <div className='mt-8 p-8 bg-slate-100 rounded-lg border flex flex-col items-end gap-4'>
                    <div className='space-x-4'>
                        {pdfLink && (
                            <Button variant="default">
                                {pdfLink}
                            </Button>
                        )}
                    </div>
                    <div className='w-full pdf-viewer'>
                        <DayEndLineQcReportViewer
                            details={reportDetails}
                            data={reportData}
                        />
                    </div>
                </div>
            }
        </div>
    )
}

export default DayEndLineNonQcReport